### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by tebeco** [Tvde1/GuidRecycler#11]
expected:
should have worked

actual:
don't work

repro step:
* create project
* use the package
* doesn't work

**Comment by Tvde1** [comment]
When you ask a question, make sure you include as much detail as possible. Such as code, the issue you are facing, and what you expect the result to be. Upload code here https://paste.mod.gg/ (see $code for more information on how to paste your code)

**Comment by tebeco** [comment]
$code

**Comment by tebeco** [comment]
$code

**Comment by tebeco** [comment]
https://paste.mod.gg/

**Comment by tebeco** [comment]
????
