### ISSUE TITLE
Redis ?

### ISSUE THREAD

**Issue by tebeco** [Tvde1/GuidRecycler#3]
make a recycler with a pub/sub model using stackexhange.redis as a back one to use in distributed service to even recycle more

**Comment by Tvde1** [comment]
Hi there! Thank you for suggesting this interesting idea. We appreciate your input in enhancing our C# NuGet package. The concept of implementing a recycler with a pub/sub model using StackExchange.Redis sounds promising, especially for distributed services. Currently, this idea is on our backlog for further consideration and development. We're also exploring the integration of [FusionCache](https://github.com/ZiggyCreatures/FusionCache) to complement this functionality. Your patience is highly valued, and we'll keep you updated on any progress. If you have any more suggestions or questions, please feel free to share. Thank you again for being a part of our community!
