### ISSUE TITLE
NetFx ?

### ISSUE THREAD

**Issue by tebeco** [Tvde1/GuidRecycler#7]
please make a net3.5 version for Xymanec

**Comment by Tvde1** [comment]
Hello! We appreciate your interest in having a .NET 3.5 version of our package for Xymanec. While we strive to accommodate various platforms and user needs, I'd like to explain that Guid Recycling, being a state-of-the-art design pattern, might not be compatible with the older .NET 3.5 framework. This design pattern relies on modern features and capabilities that are not available in that version.

We encourage keeping up with more recent versions of the .NET framework to leverage the latest advancements in software development. However, we understand that different scenarios may require different solutions. If there's anything else we can assist you with or if you have any further questions, please let us know. We value your feedback and engagement!
