### ISSUE TITLE
source generator

### ISSUE THREAD

**Issue by tebeco** [Tvde1/GuidRecycler#8]
why not use a source generator instead ?

**Comment by Tvde1** [comment]
Great question! Utilizing a source generator to pre-allocate GUIDs during compile time is an interesting approach. However, we need to consider a few factors. While this method could potentially enhance performance by reducing runtime overhead, there's a trade-off when it comes to the uniqueness of GUIDs. Generating GUIDs at compile time might lead to clashes and compromise their primary purpose of global uniqueness.

Moreover, pre-allocating GUIDs might result in "GUID-waste,". Unused GUIDs would accumulate, which could potentially lead to inefficiencies in terms of both memory usage and GUID management.

We're actively exploring different strategies to ensure the best balance between performance and maintaining the core characteristics of GUIDs. Your insights are greatly appreciated, and we'll take them into account as we continue to improve our package. If you have any more thoughts or suggestions, please don't hesitate to share them. Thank you for your engagement!
